### Get All Players
GET http://localhost:3000/players/


### Get Single Player
GET http://localhost:3000/players/7

### Update Player
PUT http://localhost:3000/players/7
Content-Type: application/json

{
  "playerName": "Praveen"
}

### Get Single Match
GET http://localhost:3000/matches/18

### Get Player All Matches
GET http://localhost:3000/players/1/matches

### Get Players of Single Match
GET http://localhost:3000/matches/2/players

### Statistics
GET http://localhost:3000/players/3/playerScores