### Get All States
GET http://localhost:3000/states/

### Get Single State
GET http://localhost:3000/states/8/

### Add District
POST http://localhost:3000/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

### Get Single District
GET http://localhost:3000/districts/66


### Delete Single District
DELETE http://localhost:3000/districts/67

### Update District
PUT http://localhost:3000/districts/66
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

### Get Total Cases
GET http://localhost:3000/states/4/stats/

### Get StateName
GET  http://localhost:3000/districts/7/details/