### Get All Movies
GET http://localhost:3000/movies/

### Add Movie
POST http://localhost:3000/movies/
Content-Type: application/json

{
   "directorId": 6,
  "movieName": "Praveen Park",
  "leadActor": "Jeff Gol"
}


###  Get Single Movie
GET http://localhost:3000/movies/50


### Update Movie
PUT http://localhost:3000/movies/50
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

### Delete Movie
DELETE http://localhost:3000/movies/50

### Get All Directors
GET http://localhost:3000/directors/

### Get Single Director Movies
GET http://localhost:3000/directors/13/movies
