
### Home
GET http://localhost:3004/


### Register User API
POST http://localhost:3004/user
Content-Type: application/json

{
  "username": "praveen123",
  "name": "Ande Praveen",
  "password": "8185995403",
  "gender": "Male",
  "location": "Hyderabad"
}

### Login User API
POST http://localhost:3004/login
Content-Type: application/json

{
  "username": "praveen123",
  "password": "8185995403"

}
