/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponse400
 */
export interface ErrorResponse400 {
    /**
     * 
     * @type {number}
     * @memberof ErrorResponse400
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse400
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorResponse400 interface.
 */
export function instanceOfErrorResponse400(value: object): value is ErrorResponse400 {
    return true;
}

export function ErrorResponse400FromJSON(json: any): ErrorResponse400 {
    return ErrorResponse400FromJSONTyped(json, false);
}

export function ErrorResponse400FromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse400 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ErrorResponse400ToJSON(value?: ErrorResponse400 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

