/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoResponse
 */
export interface TodoResponse {
    /**
     * 
     * @type {number}
     * @memberof TodoResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the TodoResponse interface.
 */
export function instanceOfTodoResponse(value: object): value is TodoResponse {
    return true;
}

export function TodoResponseFromJSON(json: any): TodoResponse {
    return TodoResponseFromJSONTyped(json, false);
}

export function TodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function TodoResponseToJSON(value?: TodoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

